// 実在コースの雰囲気を再現した独自レイアウト（全長は実際の約 45%）。角度・半径は運転者から見た向き
export const DESIGNS = {
  'eight-hills': { // 鈴鹿風（8 の字。中央でほぼ直角に立体交差）
    name: 'Eight Hills GP', sub: '鈴鹿風', halfWidth: 7.5, turn: 0,
    cmds: [
      ['mark', 'start'], ['S', 300, 'adj'],
      ['mark', 't1'], ['R', 60, 70], ['R', 30, 90], ['mark', 't2End'], ['S', 60],
      ['mark', 'esses'], ['L', 35, 55], ['R', 35, 60], ['L', 35, 55], ['R', 35, 50], ['mark', 'dunlop'], ['L', 50, 70], ['S', 90],
      ['mark', 'degner'], ['R', 30, 60], ['S', 30], ['R', 22, 60], ['mark', 'degnerEnd'], ['S', 120],
      ['mark', 'under'], ['S', 100], ['mark', 'hairpin'], ['L', 14, 170], ['mark', 'hairpinEnd'], ['S', 80], ['R', 80, 30], ['S', 100],
      ['mark', 'spoon'], ['L', 45, 90], ['L', 35, 80], ['mark', 'spoonEnd'], ['S', 120],
      ['mark', 'over'], ['S', 200, 'adj'],
      ['mark', 'r130'], ['L', 65, 60], ['S', 80],
      ['mark', 'casio'], ['R', 10, 70], ['L', 10, 70], ['mark', 'casioEnd'], ['S', 40],
      ['mark', 'final'], ['R', 55, 160, 'auto'], ['S', 60],
    ],
    // バックストレート（over）がデグナー後の区間（under）の 8m 上を通る
    elevation: [['start', 4], ['t1', 3], ['esses', 6], ['dunlop', 8], ['degner', 6], ['degnerEnd', 1], ['under', 0], ['hairpin', 1],
      ['spoon', 6], ['spoonEnd', 10], ['over', 12], ['r130', 11], ['casio', 6], ['final', 4]],
    banks: [],
    sections: [],
  },
  'speed-temple': { // モンツァ風（右回り）
    name: 'Speed Temple', sub: 'モンツァ風', halfWidth: 7.5,
    cmds: [
      ['mark', 'start'], ['S', 480, 'adj'],
      ['mark', 'rettifilo'], ['R', 12, 80], ['L', 12, 80], ['mark', 'rettifiloEnd'],
      ['S', 120], ['mark', 'grande'], ['R', 85, 70], ['mark', 'grandeEnd'], ['S', 260],
      ['mark', 'roggia'], ['L', 15, 60], ['R', 15, 60], ['S', 150],
      ['mark', 'lesmo1'], ['R', 38, 80], ['S', 60], ['mark', 'lesmo2'], ['R', 32, 70],
      ['S', 420],
      ['mark', 'ascari'], ['L', 30, 40], ['R', 26, 60], ['L', 40, 40], ['mark', 'ascariEnd'],
      ['S', 420, 'adj'],
      ['mark', 'parabolica'], ['R', 60, 170, 'auto'], ['mark', 'parabolicaEnd'],
      ['S', 60],
    ],
    elevation: [['start', 0], ['grandeEnd', 1.5], ['lesmo2', 3], ['ascari', 2], ['parabolica', 0.5]],
    banks: [['parabolica', 'parabolicaEnd', 8, 'R']],
    sections: [],
  },
  'forest-ring': { // スパ風（右回り）
    name: 'Forest Ring', sub: 'スパ風', halfWidth: 7.5,
    cmds: [
      ['mark', 'start'], ['S', 120],
      ['mark', 'source'], ['R', 16, 165], ['mark', 'sourceEnd'], ['S', 170],
      ['mark', 'eauRouge'], ['L', 40, 30], ['R', 45, 45], ['L', 60, 15], ['mark', 'raidillonTop'],
      ['S', 450, 'adj'],
      ['mark', 'combes'], ['R', 25, 60], ['L', 25, 60], ['S', 60],
      ['mark', 'malmedy'], ['R', 35, 70], ['S', 80],
      ['mark', 'rivage'], ['R', 18, 140], ['S', 90], ['L', 45, 60], ['S', 140],
      ['mark', 'pouhon'], ['L', 55, 110], ['mark', 'pouhonEnd'], ['S', 160],
      ['mark', 'fagnes'], ['R', 30, 45], ['L', 30, 45], ['S', 60],
      ['mark', 'stavelot'], ['R', 40, 90, 'auto'], ['S', 300, 'adj'],
      ['mark', 'blanchimont'], ['L', 140, 20], ['S', 60], ['L', 140, 15], ['S', 120],
      ['mark', 'busstop'], ['R', 12, 70], ['L', 12, 70], ['mark', 'busstopEnd'], ['S', 60],
    ],
    // ラ・ソース → オー・ルージュの谷 → ケメルの丘 → スタヴロの谷 → ブランシモンを登って戻る
    elevation: [['start', 14], ['source', 15], ['eauRouge', 6], ['raidillonTop', 14], ['combes', 20], ['rivage', 14],
      ['pouhon', 9], ['fagnes', 6], ['stavelot', 2], ['blanchimont', 6], ['busstop', 12]],
    banks: [],
    sections: [],
  },
  'river-park': { // イモラ風（左回り）
    name: 'River Park', sub: 'イモラ風', halfWidth: 7,
    cmds: [
      ['mark', 'start'], ['S', 300, 'adj'],
      ['mark', 'tamburello'], ['L', 15, 55], ['R', 15, 55], ['L', 40, 30], ['S', 200],
      ['mark', 'villeneuve'], ['R', 15, 55], ['L', 15, 55], ['S', 80],
      ['mark', 'tosa'], ['L', 18, 140], ['S', 120],
      ['mark', 'piratella'], ['L', 40, 50], ['S', 120, 'adj'],
      ['mark', 'acque'], ['R', 30, 80], ['L', 40, 40], ['S', 160],
      ['mark', 'alta'], ['R', 12, 55], ['L', 12, 55], ['S', 220],
      ['mark', 'rivazza'], ['L', 30, 80], ['S', 40], ['L', 25, 80], ['S', 150],
      ['mark', 'final'], ['L', 80, 40, 'auto'], ['S', 80],
    ],
    elevation: [['start', 4], ['tamburello', 3], ['tosa', 6], ['piratella', 14], ['acque', 6], ['alta', 13], ['rivazza', 2], ['final', 4]],
    banks: [],
    sections: [['acque', 'alta', 'rough']],
  },
};
